openai_api_key: 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
youtube_api_key: AIzaSyBB5UdfPyWvyEXIbutCSD40GUw1ZI_VBF8
